### ISSUE TITLE
WSA build

### ISSUE THREAD

**Issue by foriero** [dave-hillier/disruptor-unity3d#3]
Hi, in wsa build we face that MemoryBuffer() and SpinWait() do not exists. Any idea how to rewrite the code so that it works also in WSA builds?

**Comment by dave-hillier** [comment]
Can you provide steps to reproduce this?

**Comment by dave-hillier** [comment]
It looks like here are the recommended changes:

https://msdn.microsoft.com/en-gb/library/br230302.aspx#threading

**Comment by foriero** [comment]
Hi, for the MemoryBarier it was easy. Instead of Thread.MemoryBarier() it is Interlocked.MemoryBarier().

But not sure what to put there instead SpinWait. This one is a bit more tricky. Can you help with that?

**Comment by dave-hillier** [comment]
`SpinWait` can safely be replaced with `Thread.Sleep(0);` or `Thread.Yield()` - although it will change the performance characteristics (although you might never be able to tell)
