### ISSUE TITLE
32 Threads with Ringed Buffers blows up unity

### ISSUE THREAD

**Issue by NVentimiglia** [dave-hillier/disruptor-unity3d#7]
In my quest for benchmarks, I have blown up unity. In this instance, I passed in 32. Maybe not applicable to a client, but for a server. Similar tests going against the que and lock passed. this test pushed my CPU to 100, and locked up my machine (hard reset).

```

 public void BenchmarkRing(int count)
        {
            for (int t = 0; t < TESTS; t++) // 15
            {
                COUNTER = 0;
                var list = new List<Thread>();
                var que = new RingBuffer<int>(count);
                var watch = new Stopwatch();
                for (int i = 0; i < count; i++)
                {
                    list.Add(new Thread(() =>
                    {
                        while (COUNT >= COUNTER) // 100,000
                        {
                            que.Enqueue(COUNTER++);
                        }
                        watch.Stop();
                    }));
                    list.Add(new Thread(() =>
                    {
                        while (COUNT >= COUNTER)
                        {
                            int c = 0;
                            que.TryDequeue(out c);
                        }
                        watch.Stop();
                    }));
                }


                watch.Start();
                for (int i = 0; i < list.Count; i++)
                {
                    list[i].Start();
                }

                while (COUNT >= COUNTER)
                {
                    Thread.Sleep(100);
                }

                UnityEngine.Debug.LogWarning("BenchmarkRing - Threads : " + list.Count + " | ms :" + watch.ElapsedMilliseconds);
                GC.Collect();

            }
        }
```

**Comment by dave-hillier** [comment]
Not sure what I can do about this

**Comment by NVentimiglia** [comment]
Ill do another pass this weekend see what I can find

**Comment by dave-hillier** [comment]
The ring buffer is supposed to be single consumer-single producer; you've got 32 on the one buffer
From the first paragraph of Readme.md
> Only supports a single producer/single consumer. 

I'd suggest you use https://github.com/disruptor-net/Disruptor-net if you want something more complex.

**Comment by nxrighthere** [comment]
@NVentimiglia for a high-parallelism degree where you need multi-producer multi-consumer bounded queue you can use [ConcurrentBuffer](https://github.com/nxrighthere/NetStack/blob/master/Source/NetStack.Threading/ConcurrentBuffer.cs) from NetStack. But be aware of [CMPXCHG instruction](http://joeduffyblog.com/2009/01/08/some-performance-implications-of-cas-operations/) scalability and measure stuff.
