### ISSUE TITLE
Could you explain this to me?

### ISSUE THREAD

**Issue by sebas77** [dave-hillier/disruptor-unity3d#8]
https://github.com/dave-hillier/disruptor-unity3d/blob/717491f41d8663949b2d05056bb42bde17f61ce3/DisruptorUnity3d/Assets/RingBuffer.cs#L89

I am trying to understand what you wanted to achieve with this while here. I suspect you were waiting for a dequeue, but this would enter in an infinite loop in a single threaded scenario. I don't know where the data structure is going to be used, so I need it to work under any scenario. I can reproduce the deadlock.

**Comment by sebas77** [comment]
OK it seems that the deadlock was due to a bug of mine, but I would like to understand the logic anyway if you have the time.

Edit: I got the gist of it now, but I still wonder how can I make enter in a deadlock without even using multiple threads. Somehow is due to the code crashing somewhere tho.

**Comment by dave-hillier** [comment]
The queue is designed to block when you reach full capacity. A typical scenario is a producer-consumer inter-thread communication. Once the queue becomes full, I thought it was sensible behaviour to stop that thread.

For more information about disruptor see here: https://lmax-exchange.github.io/disruptor/

**Comment by sebas77** [comment]
Ok that's what I couldn't understand. It's a circular buffer isn't it? How can it get to the full capacity therefore? Shouldn't it just loop around? @dave-hillier

**Comment by sebas77** [comment]
ah thank you for the disruptor link! I guess you are suggesting me to updated to the latest version then, although I notice that in that implementation the ringbuffer is actually a publisher/consumer and not just a circular buffer. I actually created my publisher/consumer on top of your implementation.

**Comment by dave-hillier** [comment]
I am not sure what your question is or the problem you have.

It is designed to be a replacement to a replacement for something like concurrent queue. The fact it is a ring buffer is an implementation detail. 

From Readme
> I wanted to replace the ConcurrentQueue with something that did not have any extra allocation overhead. A circular buffer is a fixed size data structure that could be used in this case. When searching for an existing implementation I remembered the Disruptor; a high performance lockless queue. Disruptor has many good qualities, but in my case, I only care about the lack of allocations.
